### ISSUE TITLE
Spacing for header

### ISSUE THREAD

**Issue by briannaneet** [briannaneet/more-than-just-datum#1]
@muxlowc

I've not finished the rest of the webpage, but I'm having some trouble figuring out what classes I should apply to the header and its children to space it. 

<img width="323" alt="Screen Shot 2020-04-22 at 10 57 14 AM" src="https://user-images.githubusercontent.com/55240989/79997943-17ec4400-8488-11ea-84b9-8456de23c59a.png">

**Comment by muxlowc** [comment]
@briannaneet so first thing, is to think about the header as a grid/unit as well. So you will technically have 2 grids, each with 2 units (looks like you already got the second grid started)

You can also add the logo image inside of an h1: `<h1><img...></h1>` - since there really isnt any other place that the h1 would really make sense

I'll attached an image of the high level html for the header - hopefully that helps a bit
<img width="671" alt="Screen Shot 2020-04-22 at 1 04 02 PM" src="https://user-images.githubusercontent.com/59422623/80011478-ec725500-8499-11ea-90ed-75f77a3c28e7.png">
Hopefully this helps with the spacing a bit!

(hint: when it comes to the form/label (ie search bar): You can put your image inside of the label :)
```
<form class="relative" action="#">
        <label class="search-icon icon i-18 pin-lc" for="find" title="Search"> 
            <img.......></label>
        <input......>
</form>
```

**Comment by briannaneet** [comment]
@muxlowc Thanks again, about to submit it :)
